name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  freezed: ^2.4.3
  build_runner:
  mockito: ^5.0.16