name: network_retrofit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  get_it:
  injectable:
  dependency_injection: 1.0.0
  shared: 1.0.0
  data: 1.0.0
  config: 1.0.0
  dio:
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.1.1
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  injectable_generator:
  build_runner:
  mockito: ^5.0.16
  lints: ^3.0.0
  test: ^1.24.0
  freezed: ^2.4.3

