name: database_realm
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  get_it:
  injectable:
  dependency_injection: 1.0.0
  realm: ^20.0.1
  shared: 1.0.0
  data: 1.0.0
  config: 1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  injectable_generator:
  build_runner:
  mockito: ^5.0.16
